[metadata]
name = deephaven_plugin_node_editor
description = Graphical node editor plugin for Deephaven, with JSON, dict, and HOCON input support
long_description = file: README.md
long_description_content_type = text/markdown
version = 0.0.1
keywords = deephaven, plugin, node, graph, editor, hocon
author = Deephaven
author_email = Anonymous
platforms = any

[options]
package_dir=
    =src
packages=find_namespace:
install_requires =
    deephaven-core>=0.35.1
    deephaven-plugin>=0.6.0
    deephaven-plugin-utilities
    deephaven-plugin-ui
    pyhocon>=0.3.60
include_package_data = True

[options.packages.find]
where=src
# Keep stray Python files under src/js/node_modules out of the wheel.
exclude=
    js
    js.*

[options.entry_points]
deephaven.plugin =
    registration_cls = deephaven_plugin_node_editor.register:DeephavenPluginNodeEditorRegistration
